steps:
- name: gcr.io/cloud-builders/gcloud
  env:
    - 'load_balancer=$_LOAD_BALANCER'
    - 'project=$_PROJECT'
  entrypoint: "bash"
  args: ['./renew-certificate.sh']
options:
  logging: CLOUD_LOGGING_ONLY